# Dictionnaires de traduction pour l'interface FR <-> EN

LANGUAGES = {
    'fr': {
        "tab1": "paramètres généraux",
        "tab2": "paramètres à un calcul muVT, NPT et NPT#0",
        "tab3": "paramètres de la supermaille et des défauts ponctuels",
        "tab4": "options défauts chargés",
        "tab5": "options des défauts complexes",
        'file': "Fichier",
        'open': "Ouvrir...",
        'save': "Enregistrer sous...",
        'quit': "Quitter",
        'language': "Langue",
        'french': "Français",
        'english': "Anglais",
        'comment': "Commentaire :",
        'basename': "Base du nom des fichiers de sortie :",
        'chem_types': "Nombres de types chimiques (total, intrinsèque) :",
        'n_sublattices': "Nombre de sous-réseaux :",
        'interstitial': "Sous-réseaux interstitiels :",
        'interstitial_present': "Présent",
        'intrinsic_interstitial': "Interstitiels intrinsèques :",
        'intrinsic_interstitial_present': "Pris en compte",
        'n_sublattices_intrinsic': "Sous-réseaux occupés (état fondamental) :",
        'sites_per_cell': "Sites par maille (par sous-réseau, séparés par espace) :",
        'complex_defects': "Défauts complexes :",
        'complex_defects_present': "Présents",
        'temperature': "Température (K) :",
        'pressure': "Pression externe (kbar) :",
        'ref_energies': "Énergies de référence (eV/atome, séparées par espace) :",
        'thermo_mode': "Grandeurs thermodynamiques :",
        'by_atom': "Par atome (A/a)",
        'by_cell': "Par maille (M/m)",
        'free_energy_type': "Énergie libre par atome :",
        'total': "Totale (T/t)",
        'formation': "Formation (F/f)",
        'calc_type': "Type de calcul :",
        'dp_charges': "DP chargés (0/1, mode muVT seul) :",
        'file_loaded': "Fichier chargé",
        'file_saved': "Fichier enregistré",
        'file_load_error': "Erreur lors de l'ouverture du fichier",
        'file_save_error': "Erreur lors de l'enregistrement",
        'tab1_placeholder': "Contenu de l’onglet 1 à définir",
    },
    'en': {
        "tab1": "general parameters",
        "tab2": "parameters for a muVT, NPT and NPT#0 calculation",
        "tab3": "supercell and point defect parameters",
        "tab4": "charged point defect options",
        "tab5": "complexes point defect options",
        'file': "File",
        'open': "Open...",
        'save': "Save as...",
        'quit': "Quit",
        'language': "Language",
        'french': "French",
        'english': "English",
        'comment': "Comment:",
        'basename': "Output file basename:",
        'chem_types': "Number of chemical species (total, intrinsic):",
        'n_sublattices': "Number of sublattices:",
        'interstitial': "Interstitial sublattices:",
        'interstitial_present': "Present",
        'intrinsic_interstitial': "Intrinsic interstitials:",
        'intrinsic_interstitial_present': "Considered",
        'n_sublattices_intrinsic': "Sublattices occupied (ground state):",
        'sites_per_cell': "Sites per cell (per sublattice, space separated):",
        'complex_defects': "Complex defects:",
        'complex_defects_present': "Present",
        'temperature': "Temperature (K):",
        'pressure': "External pressure (kbar):",
        'ref_energies': "Reference energies (eV/atom, space separated):",
        'thermo_mode': "Thermodynamic quantities:",
        'by_atom': "Per atom (A/a)",
        'by_cell': "Per cell (M/m)",
        'free_energy_type': "Free energy per atom:",
        'total': "Total (T/t)",
        'formation': "Formation (F/f)",
        'calc_type': "Calculation type:",
        'dp_charges': "Charged DP (0/1, muVT mode only):",
        'file_loaded': "File loaded",
        'file_saved': "File saved",
        'file_load_error': "Error opening file",
        'file_save_error': "Error saving file",
        'tab1_placeholder': "Tab 1 content to be defined",
    }
}
